### PR TITLE
syntax extension => macro_rules

### PR DESCRIPTION
**Pull request by durka**
Hi there! I saw your project on reddit and I figured the syntax extension could be done with a simple macro. I think this has the same functionality, but I've never written a syntax extension so it's possible I misread your code.

### CODE REVIEW

**Comment by durka** [comment]
Fascinating, the CI tests fail on the server. They pass when I run them locally.

**Comment by birkenfeld** [comment]
Thanks, I suspected that something simpler was possible.

Unfortunately there seems to be a problem with how Rust handles the docstrings: if they contain double quotes, they are not escaped and the generated code contains e.g.

```
#[doc = r" Provides runtime errors."]
#[doc = r""]
#[doc =
      r" The term "runtime error" is actually a bit misleading: the errors produced by the"]
```

May be a bug in rustc?

**Comment by durka** [comment]
I see also that `MODULE_CODE_STR` is supposed to contain the actual "mod { }" statement, not just the code in it, which is why the tests failed.

**Comment by birkenfeld** [comment]
I had another hard look at the builtin macros, and I think I can use `include_str!()` to do it without any custom.

Well, at least now I have a machine gun^W^W^W^W know how to write syntax extensions :D

**Comment by durka** [comment]
Hmm, seems like that should work too yes.

**Comment by birkenfeld** [comment]
Thanks again!

**Comment by durka** [comment]
I'm going to report the doc-quote thing as a bug. Handling of doc-comments and macros was recently fixed with regards to the initial slashes, but that fix seems to have left another bug in its wake.

**Comment by birkenfeld** [comment]
BTW, the reason the tests passed for you is probably that you didn't run them with `--compiled`. I should make that the default, actually, as well as `--short`.

**Comment by birkenfeld** [comment]
> I'm going to report the doc-quote thing as a bug.

Great!

**Pull request closed without merging**
